version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - /Volumes/DATA/sites:/var/www/html:cached
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
        links:
            - php
            - nodejs
        networks:
            - app-network
    php:
        container_name: php
        build: ./php/
        volumes:
            - /Volumes/DATA/sites:/var/www/html:cached
        links:
            - mariadb
            - mongo
            - redis
        networks:
            - app-network
    nodejs:
        container_name: nodejs
        build: ./nodejs/
        environment:
            NODE_ENV: development
        volumes:
            - /Volumes/DATA/sites:/var/www/html:cached
        links:
            - mariadb
            - mongo
            - redis
        networks:
            - app-network
    mariadb:
        container_name: mariadb
        image: mariadb:latest
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
        networks:
            - app-network
    mongo:
        container_name: mongo
        image: mongo:latest
        ports: 
            - 27017:27017
        networks:
            - app-network 
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - app-network
networks:
    app-network:
        driver: bridge